// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dPv05oe97GxqWCkY-RDQH911WC7LGVQ',
    appId: '1:128610348029:android:324ad3a3732c79e3a80794',
    messagingSenderId: '128610348029',
    projectId: 'amingo-230605',
    storageBucket: 'amingo-230605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmzZ_suNKUVMwMRGU0in2s9zS-R9eaiQw',
    appId: '1:128610348029:ios:e24454009b4edbb2a80794',
    messagingSenderId: '128610348029',
    projectId: 'amingo-230605',
    storageBucket: 'amingo-230605.firebasestorage.app',
    androidClientId: '128610348029-fmdhokk79r7uj8tlul9t3q38asbnjv5o.apps.googleusercontent.com',
    iosClientId: '128610348029-tgn98r6hhpm5q53t4ljp06mtodh6okb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.amingo',
  );

}